<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit281b30d9dcc5e0fccb0e83629018e5db
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Pokedex\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Pokedex\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit281b30d9dcc5e0fccb0e83629018e5db::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit281b30d9dcc5e0fccb0e83629018e5db::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
